### ISSUE TITLE
hotend and heated bed temp always the same

### ISSUE THREAD

**Issue by terrorhai** [johnnyruz/OctoPrint-OctoVox#19]
Alexa always reports both temperatuers, but always uses the hotend temp as the same as the heated bed one.
Using it in the german version.

**Comment by johnnyruz** [comment]
Thank you for reporting this!! Definitely a bug introduced when localizing the response strings. I just pushed an update to the skill so this should now be resolved. Please test and validate.

**Comment by terrorhai** [comment]
Tested and everything works 👍
