### ISSUE TITLE
Octovox Alexa Skill not showing in search results

### ISSUE THREAD

**Issue by ashleycawley** [johnnyruz/OctoPrint-OctoVox#4]
The 'Octovox' skill does not show up for me here in the UK when I search the Alexa Skills section in neither the iOS App nor the alexa.amazon.co.uk website.

I'm guessing perhaps it may be a country based restriction at this point? Do you need to enable the Skill to be accessible in more counteries or is it yet to be approved in the UK?

Thanks for your time and sharing of this wonderful Plugin.

**Comment by johnnyruz** [comment]
@ashleycawley thanks for letting me know. I have the distribution set to "All Countries and Regions Where Alexa Distributes Skills" so it should be available, but I'm definitely looking into this and will let you know what I find.

**Comment by xyzo** [comment]
Hi, same issue for me for german users. The skill is not showing up.
And I could help translating it as well if needed... :-)

**Comment by johnnyruz** [comment]
I just got a confirmation e-mail back from Amazon that the skill should now be live in the following regions: English (IN), English (AU), English (US), English (CA), English (UK). I would love feedback if that is indeed the case.

**Comment by rocky00717** [comment]
Not in CA yet

**Comment by johnnyruz** [comment]
> Not in CA yet

If you hit [this link](https://www.amazon.ca/dp/B07WFZ8PDX) do you see it?

**Comment by rocky00717** [comment]
@johnnyruz yes I can see it through the browser but not the iphone app.

**Comment by johnnyruz** [comment]
> @johnnyruz yes I can see it through the browser but not the iphone app.

Alright, if you enable the skill through that browser (I assume linked to your Amazon Account) does it then work on your Alexa App and Echo Devices? I'm wondering if it's just a timing thing where the store takes awhile to actually update.

**Comment by rocky00717** [comment]
@johnnyruz yes all is working once I enable it through the browser.

**Comment by johnnyruz** [comment]
Fantastic! Thank you @rocky00717.

Hopefully it appears in the store soon! But in the meantime here a links to the app in the store for the available regions:

[Australia](https://www.amazon.com.au/dp/B07WFZ8PDX)
[Canada](https://www.amazon.ca/dp/B07WFZ8PDX)
[India](https://www.amazon.in/dp/B07WFZ8PDX)
[UK](https://www.amazon.co.uk/dp/B07WFZ8PDX)
[US](https://www.amazon.com/dp/B07WFZ8PDX)

**Comment by dronkos** [comment]
i can confirm that UK version works. Thank you!!

**Comment by leon-th** [comment]
I could translate it to German if someone tells me where to find the voice / text files.
Leon T

**Comment by leon-th** [comment]
I could translate it to German if someone tells me where to find the voice / text files.
Leon T

**Comment by ashleycawley** [comment]
I see it now in the UK Skills! Just enabled and gona try setup.

**Comment by ashleycawley** [comment]
It is now working for me in the UK :-) Time to get to know this Plugin! Thank you once again.

**Comment by iviar** [comment]
I see you closed the issue, but It is still not showing in the italian (it) region and possibly whole Europe region: Germany (de), Switzerland (ch), etc..
