### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by bill-orange** [johnnyruz/OctoPrint-OctoVox#6]
Well yesterday Octovox worked just fine.  Today is say that Octopi has not updated it in 23+ hours.  I checked my registration and it said that registration could not be found.  I went to the registration web sit and all looked fine.

Based on all of the above, I suspect that your sever is down.  Are you hosting it locally or using Amazon S3?

**Comment by johnnyruz** [comment]
Hey @bill-orange,

I've checked but I'm not seeing any issues server-side and most printers are successfully updating their status. The "primary key" for each printer is the combination of Name and Unique Code, so if you decide that you want Alexa to say a different name for your printer and you change it in the settings, you'll have to create a new registration for that printer and use the Unique ID that Octovox assigns for that printer name. So make sure the PrinterName and the Unique ID box in Settings match up when you click "Verify Printer". If you register a new printer name Alexa will continue to report the status for both for 10 days in which case the one that hasn't been reporting will be removed.

Admittedly this may be a bit crude and I'm definitely looking for ways to continuously improve the flow and user experience, so things like being able to easily change your printer name or remove printers without waiting 10 days are on the list for enhancements.

Let me know if you still have issues and I'll make sure you get back up and running.

FYI, everything is hosted in Microsoft Azure.

**Comment by bill-orange** [comment]
Good call.  I did change the name during the process of setup (first name was too long to be practical).  I registered the app and still no joy until I rebooted octopi.  Re-registering and rebooting octopi appears to solve the problem.  The original name will show up for 10 days I suppose.  Thanks.

**Comment by johnnyruz** [comment]
Thanks for confirming.

Yes the old name will still report for a default of 10 days. If gets super annoying before then, shoot me a PM on the octoprint forum and I'll manually remove the old printer.
