### ISSUE TITLE
Need non-English/french version of Google Gactions

### ISSUE THREAD

**Issue by ejay-ibm** [johnnyruz/OctoPrint-OctoVox#7]
Same enhancement request as #5 But for google french users. 
Thank you

**Comment by blackhawk92** [comment]
Would also really like a german version since my Google Home doesn't let me use the english version here in Germany (talking to it in english). I can help with (german) translations as soon as translations are supported at all.

**Comment by johnnyruz** [comment]
Thanks @ejay-ibm and @blackhawk92 ,

See my comment on issue #5 . Hoping to get this resolved very soon!

**Comment by ejay-ibm** [comment]
Thanks for your update. Count on me for any french translation you need.
