### ISSUE TITLE
Cannot de-register a printer

### ISSUE THREAD

**Issue by darraghbr** [johnnyruz/OctoPrint-OctoVox#8]
I do not see a way to manually de-register a printer or to rename a printer that has already been registered. 

This would be helpful as I first gave my printer a name that sounds really daft when Alexa says it out loud. I changed the name and went through registration again, but now I have two printers and Alexa reads the state of both printers when prompted.

**Comment by johnnyruz** [comment]
Hi @darraghbr,

You're right that's definitely a feature that I'm going to add soon (maybe a week or so is my estimate). As it's configured now that second printer will disappear after 10 days of the system not seeing any status updates.

I'll leave this open as an enhancement so I can track it. If that second printer gets super annoying shoot me a PM on the OctoPrint Community Forum and I'll manually remove it.

**Comment by johnnyruz** [comment]
Hello @darraghbr,

I've just pushed an update to the Backend API code that allows for users to remove a printer from their registration. If you click on the Request Printer Registration button in the settings view within OctoPrint, it will either create a new registration if the printer name you have selected does not yet exist on your account. It will also list all of the printers you currently have registered and allow you to delete them.

So if you want to rename your printer:
1. Update the name in the Printer Name box
2. Click "Request Printer Registration"
3. Record the unique code to complete the setup process
4. Click "Delete" next to the printer(s) previously registered that you want to remove

The 10 day auto-deletion policy is still in place.

**Comment by darraghbr** [comment]
Tested the deletion feature, works great!
