### ISSUE TITLE
Failed Authorization

### ISSUE THREAD

**Issue by juergenschubert** [johnnyruz/OctoPrint-OctoVox#9]
Why do I get a Failed Authorization when I try to register with a web.de email address. Tried to change the password several times but still not working.Printer name into the plugin was "my little printer". Do have to change it into one word??? Also tried in the plugin a printer name "mylittleprinter". Login failed !!!

**Comment by PiDocJohnson** [comment]
Failed Authorization tonight Sept 17, 2019. Server issues?

**Comment by johnnyruz** [comment]
Hello @juergenschubert and @PiDocJohnson,

My apologies, issue with some application keys that should now be resolved!

Please confirm and if it's now working close this issue. Thanks for bringing this to my attention!

**Comment by juergenschubert** [comment]
fixed and working for me now . Thanks

**Comment by PiDocJohnson** [comment]
Fixed and working, sorry for the delayed responce
